/* keyboard_characters.c - Keyboard handler (work in progress)
 * vim:ts=4 noexpandtab
 */

#include "keyboard_characters.h"






key dummy 			= { '\0', '\0', '\0', 0, 0 }; //this should never be pressed

/*
escape 			= { '\0', '\0', '\0', 0, 0 };
number_1 		= { '1' , '1' , '!' , 0, 1 };
number_2 		= { '2' , '2' , '@' , 0, 1 };
number_3 		= { '3' , '3' , '#' , 0, 1 };
number_4 		= { '4' , '4' , '$' , 0, 1 };
number_5 		= { '5' , '5' , '%' , 0, 1 };
number_6 		= { '6' , '6' , '^' , 0, 1 };
number_7 		= { '7' , '7' , '&' , 0, 1 };
number_8 		= { '8' , '8' , '*' , 0, 1 };
number_9 		= { '9' , '9' , '(' , 0, 1 };
number_0 		= { '0' , '0' , ')' , 0, 1 };
dash 			= { '-' , '-' , '_' , 0, 1 };
equals 			= { '=' , '=' , '+' , 0, 1 };
backspace 		= { '\0', '\0', '\0', 0, 0 };
tab 			= { '\t', '\t', '\t', 0, 1 };
q 				= { 'q' , 'Q' , 'Q' , 0, 1 };
w 				= { 'w' , 'W' , 'W' , 0, 1 };
e 				= { 'e' , 'E' , 'E' , 0, 1 };
r 				= { 'r' , 'R' , 'R' , 0, 1 };
t 				= { 't' , 'T' , 'T' , 0, 1 };
y 				= { 'y' , 'Y' , 'Y' , 0, 1 };
u 				= { 'u' , 'U' , 'U' , 0, 1 };
i 				= { 'i' , 'I' , 'I' , 0, 1 };
o 				= { 'o' , 'O' , 'O' , 0, 1 };
p 				= { 'p' , 'P' , 'P' , 0, 1 };
left_bracket 	= { '[' , '[' , '{' , 0, 1 };
right_bracket 	= { ']' , ']' , '}' , 0, 1 };
enter 			= { '\n', '\n', '\n', 0, 1 };
left_control 	= { '\0', '\0', '\0', 0, 0 };
a 				= { 'a' , 'A' , 'A' , 0, 1 };
s 				= { 's' , 'S' , 'S' , 0, 1 };
d 				= { 'd' , 'D' , 'D' , 0, 1 };
f 				= { 'f' , 'F' , 'F' , 0, 1 };
g 				= { 'g' , 'G' , 'G' , 0, 1 };
h 				= { 'h' , 'H' , 'H' , 0, 1 };
j 				= { 'j' , 'J' , 'J' , 0, 1 };
k 				= { 'w' , 'W' , 'W' , 0, 1 };
l 				= { 'l' , 'L' , 'L' , 0, 1 };
semicolon 		= { ';' , ';' , ':' , 0, 1 };
single_quote 	= { '\'', '\'', '\"', 0, 1 };
back_tick 		= { '`' , '`' , '~' , 0, 1 };
left_shift 		= { '\0', '\0', '\0', 0, 0 };
backslash 		= { '\\', '\\', '|' , 0, 1 };
z 				= { 'z' , 'X' , 'Z' , 0, 1 };
x 				= { 'x' , 'X' , 'X' , 0, 1 };
c 				= { 'c' , 'C' , 'C' , 0, 1 };
v 				= { 'v' , 'V' , 'V' , 0, 1 };
b 				= { 'b' , 'B' , 'B' , 0, 1 };
n 				= { 'n' , 'N' , 'N' , 0, 1 };
m 				= { 'm' , 'M' , 'M' , 0, 1 };
comma 			= { ',' , ',' , '<' , 0, 1 };
period 			= { '.' , '.' , '>' , 0, 1 };
slash 			= { '/' , '/' , '?' , 0, 1 };
right_shift 	= { '\0', '\0', '\0', 0, 0 };
left_alt 		= { '\0', '\0', '\0', 0, 0 };
space 			= { ' ' , ' ' , ' ' , 0, 1 };
caps_lock 		= { '\0', '\0', '\0', 0, 0 };
f1 				= { '\0', '\0', '\0', 0, 0 };
f2 				= { '\0', '\0', '\0', 0, 0 };
f3 				= { '\0', '\0', '\0', 0, 0 };
f4 				= { '\0', '\0', '\0', 0, 0 };
f5 				= { '\0', '\0', '\0', 0, 0 };
f6 				= { '\0', '\0', '\0', 0, 0 };
f7 				= { '\0', '\0', '\0', 0, 0 };
f8 				= { '\0', '\0', '\0', 0, 0 };
f9 				= { '\0', '\0', '\0', 0, 0 };
f10 			= { '\0', '\0', '\0', 0, 0 };
f11 			= { '\0', '\0', '\0', 0, 0 };
f12 			= { '\0', '\0', '\0', 0, 0 };
number_lock 	= { '\0', '\0', '\0', 0, 0 };
scroll_lock 	= { '\0', '\0', '\0', 0, 0 };
keypad_1 		= { '1' , '1' , '1' , 0, 1 };
keypad_2 		= { '2' , '2' , '2' , 0, 1 };
keypad_3 		= { '3' , '3' , '3' , 0, 1 };
keypad_4 		= { '4' , '4' , '4' , 0, 1 };
keypad_5 		= { '5' , '5' , '5' , 0, 1 };
keypad_6 		= { '6' , '6' , '6' , 0, 1 };
keypad_7 		= { '7' , '7' , '7' , 0, 1 };
keypad_8 		= { '8' , '8' , '8' , 0, 1 };
keypad_9 		= { '9' , '9' , '9' , 0, 1 };
keypad_0 		= { '0' , '0' , '0' , 0, 1 };
keypad_dash 	= { '-' , '-' , '-' , 0, 1 };
keypad_plus 	= { '+' , '+' , '+' , 0, 1 };
keypad_period 	= { '.' , '.' , '.' , 0, 1 };
keypad_star 	= { '*' , '*' , '*' , 0, 1 };
keypad_enter 	= { '\n', '\n', '\n', 0, 1 };
right_control 	= { '\0', '\0', '\0', 0, 0 };
keypad_slash 	= { '/' , '/' , '/' , 0, 1 };
right_alt 		= { '\0', '\0', '\0', 0, 0 };
home 			= { '\0', '\0', '\0', 0, 0 };
cursor_up 		= { '\0', '\0', '\0', 0, 0 };
page_up 		= { '\0', '\0', '\0', 0, 0 };
cursor_left 	= { '\0', '\0', '\0', 0, 0 };
cursor_right 	= { '\0', '\0', '\0', 0, 0 };
end 			= { '\0', '\0', '\0', 0, 0 };
cursor_down 	= { '\0', '\0', '\0', 0, 0 };
page_down 		= { '\0', '\0', '\0', 0, 0 };
insert 			= { '\0', '\0', '\0', 0, 0 };
delete 			= { '\0', '\0', '\0', 0, 0 };
left_gui 		= { '\0', '\0', '\0', 0, 0 };
right_gui 		= { '\0', '\0', '\0', 0, 0 };
apps 			= { '\0', '\0', '\0', 0, 0 };
pause 			= { '\0', '\0', '\0', 0, 0 };



dummy_pressed 			= { &dummy 			, 1 }; //this should never be pressed
escape_pressed 			= { &escape  		, 1 };
number_1_pressed 		= { &number_1  		, 1 };
number_2_pressed		= { &number_2  		, 1 };
number_3_pressed		= { &number_3  		, 1 };
number_4_pressed 		= { &number_4  		, 1 };
number_5_pressed 		= { &number_5  		, 1 };
number_6_pressed 		= { &number_6  		, 1 };
number_7_pressed 		= { &number_7  		, 1 };
number_8_pressed 		= { &number_8  		, 1 };
number_9_pressed 		= { &number_9  		, 1 };
number_0_pressed 		= { &number_0 	 	, 1 };
dash_pressed 			= { &dash 	  		, 1 };
equals_pressed 			= { &equals  		, 1 };
backspace_pressed 		= { &backspace 		, 1 };
tab_pressed 			= { &tab 	  		, 1 };
q_pressed 				= { &q  	 		, 1 };
w_pressed 				= { &w  	 		, 1 };
e_pressed 				= { &e  	 		, 1 };
r_pressed 				= { &r  	 		, 1 };
t_pressed 				= { &t  	 		, 1 };
y_pressed 				= { &y  	 		, 1 };
u_pressed 				= { &u  	 		, 1 };
i_pressed 				= { &i  	 		, 1 };
o_pressed 				= { &o  	 		, 1 };
p_pressed 				= { &p  	 		, 1 };
left_bracket_pressed 	= { &left_bracket 	, 1 };
right_bracket_pressed 	= { &right_bracket  , 1 };
enter_pressed 			= { &enter  	 	, 1 };
left_control_pressed 	= { &left_control  	, 1 };
a_pressed 				= { &a 				, 1 };
s_pressed 				= { &s 				, 1 };
d_pressed 				= { &d 				, 1 };
f_pressed 				= { &f 				, 1 };
g_pressed 				= { &g 				, 1 };
h_pressed 				= { &h 				, 1 };
j_pressed 				= { &j 				, 1 };
k_pressed 				= { &k 				, 1 };
l_pressed 				= { &l 				, 1 };
semicolon_pressed 		= { &semicolon 		, 1 };
single_quote_pressed 	= { &single_quote	, 1 };
back_tick_pressed 		= { &back_tick 		, 1 };
left_shift_pressed 		= { &left_shift 	, 1 };
backslash_pressed 		= { &backslash 		, 1 };
z_pressed 				= { &z 				, 1 };
x_pressed 				= { &x 				, 1 };
c_pressed 				= { &c 				, 1 };
v_pressed 				= { &v 				, 1 };
b_pressed 				= { &b 				, 1 };
n_pressed 				= { &n 				, 1 };
m_pressed 				= { &m 				, 1 };
comma_pressed 			= { &comma 			, 1 };
period_pressed 			= { &period 		, 1 };
slash_pressed 			= { &slash 			, 1 };
right_shift_pressed 	= { &right_shift 	, 1 };
left_alt_pressed  		= { &left_alt 		, 1 };
space_pressed 			= { &space 			, 1 };
caps_lock_pressed 		= { &caps_lock 		, 1 };
f1_pressed 				= { &f1 			, 1 };
f2_pressed 				= { &f2				, 1 };
f3_pressed 				= { &f3				, 1 };
f4_pressed 				= { &f4				, 1 };
f5_pressed 				= { &f5				, 1 };
f6_pressed 				= { &f6 			, 1 };
f7_pressed 				= { &f7				, 1 };
f8_pressed 				= { &f8				, 1 };
f9_pressed 				= { &f9				, 1 };
f10_pressed 			= { &f10 			, 1 };
f11_pressed 			= { &f11			, 1 };
f12_pressed 			= { &f12			, 1 };
number_lock_pressed 	= { &number_lock 	, 1 };

scroll_lock_pressed;
keypad_1_pressed;
keypad_2_pressed;
keypad_3_pressed;
keypad_4_pressed;
keypad_5_pressed;
keypad_6_pressed;
keypad_7_pressed;
keypad_8_pressed;
keypad_9_pressed;
keypad_0_pressed;
keypad_dash_pressed;
keypad_plus_pressed;
keypad_period_pressed;
keypad_star_pressed;
keypad_enter_pressed;
right_control_pressed;
keypad_slash_pressed;
right_alt_pressed;
home_pressed;
cursor_up_pressed;
page_up_pressed;
cursor_left_pressed;
cursor_right_pressed;
end_pressed;
cursor_down_pressed;
page_down_pressed;
insert_pressed;
delete_pressed;
left_gui_pressed;
right_gui_pressed;
apps_pressed;
pause_pressed;


dummy_released; //this should never be pressed
escape_released;
number_1_released;
number_2_released;
number_3_released;
number_4_released;
number_5_released;
number_6_released;
number_7_released;
number_8_released;
number_9_released;
number_0_released;
dash_released;
equals_released;
backspace_released;
tab_released;
q_released;
w_released;
e_released;
r_released;
t_released;
y_released;
u_released;
i_released;
o_released;
p_released;
left_bracket_released;
right_bracket_released;
enter_released;
left_control_released;
a_released;
s_released;
d_released;
f_released;
g_released;
h_released;
j_released;
k_released;
l_released;
semicolon_released;
single_quote_released;
back_tick_released;
left_shift_released;
backslash_released;
z_released;
x_released;
c_released;
v_released;
b_released;
n_released;
m_released;
comma_released;
period_released;
slash_released;
right_shift_released;
left_alt_released;
space_released;
caps_lock_released;
f1_released;
f2_released;
f3_released;
f4_released;
f5_released;
f6_released;
f7_released;
f8_released;
f9_released;
f10_released;
f11_released;
f12_released;
number_lock_released;
scroll_lock_released;
keypad_1_released;
keypad_2_released;
keypad_3_released;
keypad_4_released;
keypad_5_released;
keypad_6_released;
keypad_7_released;
keypad_8_released;
keypad_9_released;
keypad_0_released;
keypad_dash_released;
keypad_plus_released;
keypad_period_released;
keypad_star_released;
keypad_enter_released;
right_control_released;
keypad_slash_released;
right_alt_released;
home_released;
cursor_up_released;
page_up_released;
cursor_left_released;
cursor_right_released;
end_released;
cursor_down_released;
page_down_released;
insert_released;
delete_released;
left_gui_released;
right_gui_released;
apps_released;
pause_released;
*/
