boot.o: boot.S multiboot.h x86_desc.h types.h
intel_intr.o: intel_intr.S x86_desc.h types.h
sys_calls.o: sys_calls.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
intel_intr_handlers.o: intel_intr_handlers.c lib.h types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h rtc.h \
  keyboard.h debug.h intel_intr.h sys_calls.h paging.h
keyboard.o: keyboard.c keyboard.h types.h lib.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h
rtc.o: rtc.c rtc.h types.h lib.h
sys_calls_handlers.o: sys_calls_handlers.c types.h
