boot.o: boot.S multiboot.h x86_desc.h types.h
intel_intr.o: intel_intr.S x86_desc.h types.h
sys_calls.o: sys_calls.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
intel_intr_handlers.o: intel_intr_handlers.c lib.h types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  intel_intr.h sys_calls.h
lib.o: lib.c lib.h types.h
sys_calls_handlers.o: sys_calls_handlers.c types.h
